name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # CARTÃO 1: Estatísticas Gerais (Estilo Classic/Clean)
      - name: Geral Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stats.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
      # CARTÃO 2: Apenas Linguagens Mais Usadas (Estilo Compacto)
      - name: Top Linguagens
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-langs.svg
          base: "" # Limpa o cabeçalho padrão para focar apenas nas linguagens
          plugin_languages: true
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: true # Torna a análise mais precisa
